# Generated by Django 2.1.7 on 2019-03-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=40)),
                ('changed_column', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('old_value', models.CharField(max_length=200)),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 15, 39, 38, 318326))),
                ('change_type', models.CharField(choices=[('Create', 'Created'), ('Modified', 'Modified')], max_length=10)),
            ],
            options={
                'db_table': 'pos_audit',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('product_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pos_invetory',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'pos_users',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XL', 'Extra Large')], max_length=25)),
                ('options', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete='CASCADE', related_name='variant_created_by', to='inventory.Users')),
                ('item', models.ForeignKey(on_delete='CASCADE', to='inventory.Item')),
                ('modified_by', models.ForeignKey(on_delete='CASCADE', related_name='variant_modified_by', to='inventory.Users')),
            ],
            options={
                'db_table': 'pos_variant',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete='CASCADE', related_name='created_by', to='inventory.Users'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_by',
            field=models.ForeignKey(on_delete='CASCADE', related_name='modified_by', to='inventory.Users'),
        ),
        migrations.AddField(
            model_name='audit',
            name='modified_by',
            field=models.ForeignKey(on_delete='CASCADE', to='inventory.Users'),
        ),
    ]
