# Generated by Django 2.1.7 on 2019-03-25 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 5, 12, 4, 816337)),
        ),
        migrations.AlterField(
            model_name='audit',
            name='old_value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
